package leetcode;

/**
 * Project Name : Leetcode 
 * Package Name : leetcode
 * File Name : FindtheDifference
 * Creator : Edward
 * Description : 389. Find the Difference 
 */

/**
 * Created by Edward on 25/07/2017.
 */
public class FindtheDifference {
    
     Given two strings s and t which consist of only lowercase letters.

     String t is generated by random shuffling string s and then add one more letter at a random position.

     Find the letter that was added in t
     Input:
     s = "abcd"
     t = "abcde"

     Output:
     e

     Explanation:
     'e' is the letter that was added.

     题意：给你两个字符串s和t， t比s多一个字母，除了这个多的字母以外，剩下所有的字母都相同（位置可以不同），找出这个多余的字母。

     思路：巧妙地运用异或，已获得原理为，都转换为二进制，当前位数字相同就为零，不同就为1. 这样我们一直异或下去，最后剩下的那个就是答案。

     异或:  ^ (相同为零，不同为一)

     0 0 0
     0 1 1
     1 0 1
     1 1 0
     异或举例：
     4 : 0100
     6 : 0110
         0010
     4 ：0100
         0110 ->6

     time: O(n);
     space: O(1);
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference(String s, String t) {
        char c = t.charAt(t.length() - 1);
        for (int i = 0; i < s.length(); i++) {
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }
}
